import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { tmpdir } from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { generateTests } from '../src/core/testgen.js';
import { generateText, listModelProviders } from '../src/core/llm.js';

test('generates deterministic test plan', async () => {
  const root = mkdtempSync(path.join(tmpdir(), 'htg-testgen-'));
  writeFileSync(path.join(root, 'api.ts'), 'export function loadUser(id) { return fetch(`/users/${id}`); }\n');
  const output = path.join(root, 'tests.md');
  const result = await generateTests({ root, output });
  assert.equal(result.ok, true);
  assert.equal(result.outputPath, output);
  assert.match(readFileSync(output, 'utf8'), /Generated Test Plan/);
});

test('relative test generation output resolves under project root', async () => {
  const root = mkdtempSync(path.join(tmpdir(), 'htg-testgen-relative-'));
  writeFileSync(path.join(root, 'api.ts'), 'export function loadUser(id) { return fetch(`/users/${id}`); }\n');
  const previous = process.cwd();
  process.chdir(tmpdir());
  try {
    const result = await generateTests({ root, output: 'plans/generated.md' });
    assert.equal(result.outputPath, path.join(root, 'plans', 'generated.md'));
    assert.match(readFileSync(result.outputPath, 'utf8'), /Generated Test Plan/);
  } finally {
    process.chdir(previous);
  }
});

test('test generation rejects output paths outside the project root', async () => {
  const root = mkdtempSync(path.join(tmpdir(), 'htg-testgen-outside-'));
  await assert.rejects(
    generateTests({ root, output: '../outside.md' }),
    /escapes project root/
  );
});

test('ollama test generation handles success and fallback paths', async () => {
  const root = mkdtempSync(path.join(tmpdir(), 'htg-testgen-ollama-'));
  writeFileSync(path.join(root, 'api.ts'), 'export function loadUser(id) { return fetch(`/users/${id}`); }\n');
  const previous = process.env.OLLAMA_BASE_URL;

  const okServer = await startServer((_req, res) => {
    res.setHeader('content-type', 'application/json');
    res.end(JSON.stringify({ response: '# Generated by Ollama\n\nTest timeout behavior.' }));
  });
  const badServer = await startServer((_req, res) => {
    res.writeHead(500).end('bad sk-1234567890abcdefghijklmnopqrstuvwxyzABCDE'); // holdthegoblin: allow-secret
  });
  const invalidServer = await startServer((_req, res) => {
    res.writeHead(200).end('not json');
  });
  const slowServer = await startServer(() => undefined);

  try {
    process.env.OLLAMA_BASE_URL = okServer.url;
    const ok = await generateTests({ root, provider: 'ollama', output: path.join(root, 'ok.md'), timeoutMs: 500 });
    assert.equal(ok.ok, true);
    assert.match(ok.content, /Generated by Ollama/);

    process.env.OLLAMA_BASE_URL = badServer.url;
    const bad = await generateTests({ root, provider: 'ollama', output: path.join(root, 'bad.md'), timeoutMs: 500 });
    assert.equal(bad.ok, false);
    assert.match(bad.error ?? '', /HTTP 500/);
    assert.doesNotMatch(bad.error ?? '', /abcdefghijklmnopqrstuvwxyz/);
    assert.match(bad.content, /Generated Test Plan/);

    process.env.OLLAMA_BASE_URL = invalidServer.url;
    const invalid = await generateTests({ root, provider: 'ollama', output: path.join(root, 'invalid.md'), timeoutMs: 500 });
    assert.equal(invalid.ok, false);
    assert.match(invalid.content, /Generated Test Plan/);

    process.env.OLLAMA_BASE_URL = slowServer.url;
    const timedOut = await generateTests({ root, provider: 'ollama', output: path.join(root, 'timeout.md'), timeoutMs: 20 });
    assert.equal(timedOut.ok, false);
    assert.match(timedOut.error ?? '', /abort|aborted|Abort/i);
  } finally {
    if (previous === undefined) delete process.env.OLLAMA_BASE_URL;
    else process.env.OLLAMA_BASE_URL = previous;
    await okServer.close();
    await badServer.close();
    await invalidServer.close();
    await slowServer.close();
  }
});

test('external model providers work with user subscriptions and custom endpoints', async () => {
  const root = mkdtempSync(path.join(tmpdir(), 'htg-testgen-providers-'));
  writeFileSync(path.join(root, 'api.ts'), 'export function loadUser(id) { return fetch(`/users/${id}`); }\n');
  const previous = snapshotEnv([
    'OPENAI_COMPATIBLE_BASE_URL',
    'OPENAI_COMPATIBLE_MODEL',
    'OPENAI_COMPATIBLE_API_KEY',
    'OLLAMA_CLOUD_BASE_URL',
    'OLLAMA_CLOUD_MODEL',
    'OLLAMA_API_KEY',
    'ANTHROPIC_BASE_URL',
    'ANTHROPIC_MODEL',
    'ANTHROPIC_API_KEY',
    'MINIMAX_BASE_URL',
    'MINIMAX_MODEL',
    'MINIMAX_API_KEY',
    'MINIMAX_GROUP_ID',
    'ZAI_BASE_URL',
    'ZAI_MODEL',
    'ZAI_API_KEY',
    'GLM_BASE_URL',
    'GLM_MODEL',
    'GLM_API_KEY',
    'KIMI_BASE_URL',
    'KIMI_MODEL',
    'KIMI_API_KEY',
    'MOONSHOT_BASE_URL',
    'MOONSHOT_MODEL',
    'MOONSHOT_API_KEY',
    'DEEPSEEK_BASE_URL',
    'DEEPSEEK_MODEL',
    'DEEPSEEK_API_KEY',
  ]);

  const openAiServer = await startServer(async (req, res) => {
    assert.equal(req.url, '/v1/chat/completions');
    const body = JSON.parse(await readRequestBody(req)) as { model?: string };
    if (body.model === 'MiniMax-M2.7') {
      assert.equal(req.headers.authorization, 'Bearer minimax-key');
      assert.equal(req.headers['x-minimax-group-id'], 'group-1');
    } else if (body.model === 'MiniMax-M2.5') {
      assert.equal(req.headers.authorization, 'Bearer minimax-explicit-key');
      assert.equal(req.headers['x-minimax-group-id'], 'group-2');
    }
    res.setHeader('content-type', 'application/json');
    res.end(JSON.stringify({ choices: [{ message: { content: `# ${body.model ?? 'OpenAI-compatible'} plan` } }] }));
  });
  const ollamaCloudServer = await startServer((_req, res) => {
    res.setHeader('content-type', 'application/json');
    res.end(JSON.stringify({ response: '# Ollama Cloud plan' }));
  });
  const anthropicServer = await startServer((_req, res) => {
    res.setHeader('content-type', 'application/json');
    res.end(JSON.stringify({ content: [{ type: 'text', text: '# Anthropic plan' }] }));
  });

  try {
    process.env.OPENAI_COMPATIBLE_BASE_URL = `${openAiServer.url}/v1`;
    process.env.OPENAI_COMPATIBLE_MODEL = 'custom-model';
    const openAi = await generateTests({ root, provider: 'openai-compatible', output: path.join(root, 'openai.md'), timeoutMs: 500 });
    assert.equal(openAi.ok, true);
    assert.match(openAi.content, /custom-model/);

    process.env.OLLAMA_CLOUD_BASE_URL = ollamaCloudServer.url;
    process.env.OLLAMA_CLOUD_MODEL = 'gpt-oss:120b';
    process.env.OLLAMA_API_KEY = 'ollama-key';
    const cloud = await generateTests({ root, provider: 'ollama-cloud', output: path.join(root, 'cloud.md'), timeoutMs: 500 });
    assert.equal(cloud.ok, true);
    assert.match(cloud.content, /Ollama Cloud/);

    process.env.ANTHROPIC_BASE_URL = anthropicServer.url;
    process.env.ANTHROPIC_MODEL = 'claude-test';
    process.env.ANTHROPIC_API_KEY = 'anthropic-key';
    const anthropic = await generateTests({ root, provider: 'anthropic', output: path.join(root, 'anthropic.md'), timeoutMs: 500 });
    assert.equal(anthropic.ok, true);
    assert.match(anthropic.content, /Anthropic/);

    process.env.MINIMAX_BASE_URL = `${openAiServer.url}/v1`;
    process.env.MINIMAX_MODEL = 'MiniMax-M2.7';
    process.env.MINIMAX_API_KEY = 'group-1|minimax-key';
    const minimax = await generateTests({ root, provider: 'minimax', output: path.join(root, 'minimax.md'), timeoutMs: 500 });
    assert.equal(minimax.ok, true);
    assert.match(minimax.content, /MiniMax-M2\.7/);
    const minimaxExplicitKey = await generateText({
      provider: 'minimax',
      model: 'MiniMax-M2.5',
      baseUrl: `${openAiServer.url}/v1`,
      apiKey: 'group-2|minimax-explicit-key', // holdthegoblin: allow-secret
      prompt: 'Write one test idea.',
      timeoutMs: 500,
    });
    assert.equal(minimaxExplicitKey.ok, true);
    assert.match(minimaxExplicitKey.text ?? '', /MiniMax-M2\.5/);

    process.env.ZAI_BASE_URL = `${openAiServer.url}/v1`;
    process.env.ZAI_MODEL = 'glm-5.1';
    process.env.ZAI_API_KEY = 'zai-key';
    const zai = await generateTests({ root, provider: 'zai', output: path.join(root, 'zai.md'), timeoutMs: 500 });
    assert.equal(zai.ok, true);
    assert.match(zai.content, /glm-5\.1/);

    process.env.KIMI_BASE_URL = `${openAiServer.url}/v1`;
    process.env.KIMI_MODEL = 'kimi-k2.6';
    process.env.KIMI_API_KEY = 'kimi-key';
    const kimi = await generateTests({ root, provider: 'kimi', output: path.join(root, 'kimi.md'), timeoutMs: 500 });
    assert.equal(kimi.ok, true);
    assert.match(kimi.content, /kimi-k2\.6/);

    process.env.DEEPSEEK_BASE_URL = `${openAiServer.url}/v1`;
    process.env.DEEPSEEK_MODEL = 'deepseek-v4-flash';
    process.env.DEEPSEEK_API_KEY = 'deepseek-key';
    const deepseek = await generateTests({ root, provider: 'deepseek', output: path.join(root, 'deepseek.md'), timeoutMs: 500 });
    assert.equal(deepseek.ok, true);
    assert.match(deepseek.content, /deepseek-v4-flash/);
  } finally {
    restoreEnv(previous);
    await openAiServer.close();
    await ollamaCloudServer.close();
    await anthropicServer.close();
  }
});

test('model provider registry includes common external subscription providers', () => {
  const ids = listModelProviders().map((provider) => provider.id);
  assert.deepEqual(ids, ['ollama', 'ollama-cloud', 'openai-compatible', 'openai', 'groq', 'openrouter', 'anthropic', 'minimax', 'zai', 'kimi', 'deepseek']);
  const providers = listModelProviders();
  assert.equal(providers.find((provider) => provider.id === 'kimi')?.defaultModel, 'kimi-k2.6');
  assert.equal(providers.find((provider) => provider.id === 'zai')?.defaultBaseUrl, 'https://api.z.ai/api/paas/v4');
});

async function startServer(handler: (req: IncomingMessage, res: ServerResponse) => void) {
  const server = createServer(handler);
  await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve));
  const address = server.address();
  if (!address || typeof address === 'string') throw new Error('No server address.');
  return {
    url: `http://127.0.0.1:${address.port}`,
    close: () => new Promise<void>((resolve) => server.close(() => resolve())),
  };
}

function snapshotEnv(keys: string[]): Record<string, string | undefined> {
  return Object.fromEntries(keys.map((key) => [key, process.env[key]]));
}

function restoreEnv(snapshot: Record<string, string | undefined>): void {
  for (const [key, value] of Object.entries(snapshot)) {
    if (value === undefined) delete process.env[key];
    else process.env[key] = value;
  }
}

async function readRequestBody(req: IncomingMessage): Promise<string> {
  const chunks: Buffer[] = [];
  for await (const chunk of req) chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
  return Buffer.concat(chunks).toString('utf8');
}
